### ISSUE TITLE
actual-server doesnt work with edge browser

### ISSUE THREAD

**Issue by fekhoo** [Kippenhof/docker-templates#17]
There was a problem loading the app in this browser version. If this continues to be a problem, you can [download the desktop app](https://actualbudget.com/download).
Contact [help@actualbudget.com](mailto:help@actualbudget.com) for support

**Comment by hofq** [comment]
hi, could you provide screenshots or the specific Browser/ Server version you are using?

**Comment by fekhoo** [comment]
I ma using  Microsoft Edge Version 103.0.1264.77 (Official build) (x86_64) on a MacOS
<img width="2560" alt="image" src="https://user-images.githubusercontent.com/44518355/182037612-927bd5eb-f11e-4a14-8875-0d809dd8e8da.png">

**Comment by hofq** [comment]
Hi, i would suggest u writing to [help@actualbudget.com](mailto:help@actualbudget.com) or Write in the #tech-support on [their Discord](https://discord.gg/pRYNYr4W5A) since i can't replicate the issue in my Edge (Build 103.0.1264.77, Win11 x86) and don't see how the Unraid template can interfere.

Feel free to reopen here if you can show me otherwise.
