### ISSUE TITLE
[actualserver] SQLLITE Error

### ISSUE THREAD

**Issue by ShawnHawryluk** [Kippenhof/docker-templates#29]
Seems to be some SQL LITE change within the last week or so, for actual server

/app/node_modules/better-sqlite3/lib/methods/wrappers.js:9
        this[cppdb].exec(sql);
                    ^
SqliteError: no such column: password
    at Database.exec (/app/node_modules/better-sqlite3/lib/methods/wrappers.js:9:14)
    at WrappedDatabase.exec (file:///app/src/db.js:30:20)
    at Migration.up (file:///app/migrations/1718889148000-openid.js:4:24)
    at next (/app/node_modules/migrate/lib/migrate.js:35:45)
    at /app/node_modules/migrate/lib/migrate.js:71:9
    at /app/node_modules/migrate/lib/set.js:84:5
    at FSReqCallback.oncomplete (node:fs:192:23) {
  code: 'SQLITE_ERROR'
}

Node.js v18.20.5
Checking if there are any migrations to run for direction "up"...

**Comment by hofq** [comment]
looks like an server error. I suggest you to go here:
https://github.com/actualbudget/actual-server/issues

**Comment by DeKleineKobini** [comment]
This is caused by migrations not being persisted when using this template. I've updated this template in #30 so new installs don't have this problem. Old installs will need to change to a single host path manually, and then fake the current migrations file by adding timestamps where needed.

**Comment by hofq** [comment]
The Path was Updated in the last Revision of the Template.

Please update your Template and not only the Docker image

So:
1. Downgrade the Docker image
2. Upgrade the Template
3. Upgrade Docker image back to the latest version

Edit: For Troubleshooting after the fix you can refer here
https://github.com/actualbudget/actual-server/issues/521

**Comment by dervish666** [comment]
Sorry, downgrade to which version?
Upgrade the template from what to what?

Sorry if I'm being thick but this isn't very clear.

**Comment by hofq** [comment]
> Sorry, downgrade to which version? Upgrade the template from what to what?
> 
> Sorry if I'm being thick but this isn't very clear.

1. Downgrade to the Last Version that was running by changing the tag from latest to the last version that was running. If you don't know you could try
- 24.12.0
- 24.11.0

If the App is still broken try older Versions.


2. If the app Changes back to running, go to in the Community Apps Tab and Update the Template.

3. If that was successful, go back to the latest tag.


Also: Please do Backups before Upgrades, as you can always have something break like this

**Comment by colossalsquids** [comment]
thanks heaps @hofq, that was enough to lead me down the right path. To make it easier for others, this was my step-by-step path to resolution (Unraid version 6.12.10).

1. Opened a terminal in Unraid and zipped up my actual-server directory in appdata so as to have a temporary backup:
`zip -r budget.zip actual-server`

2. Deleted my existing ActualServer container in Unraid's Docker tab

3. At the bottom of the Docker tab, click 'Add Container', then filled it in with these details:
**Template:** leave it as 'Select a template'
**Name:** ActualServer
**Repository:** actualbudget/actual-server:latest
**Network Type:** Bridge

Then added the following additional items via the '+ Add another Path, Port, Variable, Label or Device' option:
[Port] | **Web UI:** 5006
[Path] | **Host Path:** /mnt/user/appdata/actual-server
\* Note the host path is now just the root of the actual-server directory in appdata.

4. Hit apply and the container should be created. A user in the Discord (linked in the GitHub issue above) noted that this was all they had to do, but for me I had to muck around with the .migrate file

5. Now in that same terminal session from step 1, navigate to the appdata folder:
`cd /mnt/user/appdata/actual-server`

6. Edit the .migrate file present in that directory using vi:
`vi .migrate`

7. Clear the contents of the file. If you aren't familiar with vi, you can do this by typing **:%d** and pressing enter. Do nothing else - we will return in step 9

8. Now copy the contents of the .migrate file mentioned in the [issue](https://github.com/actualbudget/actual-server/issues/521)

9. Back to your terminal with vi open, press the **i** button to enter insert mode. Paste the contents of the .migrate file from the issue here, then hit **Esc**, followed by **:wq!** and enter

10. Go back to your Docker tab in Unraid and try start the container. It should boot successfully now.

11. For me, when I opened the ActualBudget web UI I noticed it was complaining about failing to sync. To resolve this I had to clear cookies from my browser (Firefox)

12. I then deleted this container, went to the Community Apps tab in Unraid, and installed ActualBudget again so that it plays nicely with Unraid again

After all this, I was back in business. This might be a bit verbose but I wanted to make it crystal clear to others who get a lot of value from this fantastic tool who were struggling

**Comment by dion1231** [comment]
@imalobster You're a lifesaver! Thank you!

**Comment by bladecell** [comment]
Did not work for me, got Server returned an error while checking its status. in the end..

**Comment by bambalam101** [comment]
> Did not work for me, got Server returned an error while checking its status. in the end..

@bladecell clear your cache and ensure HTTPS access. @imalobster solution worked for me after a cache clear.

**Comment by bladecell** [comment]
I had to map the `/mnt/user/appdata/actual-server` to `/data` in the container, now it works..
